// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtdchowzitagopmsurzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10ZGNob3d6aXRhZ29wbXN1cnppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTQ0NTEsImV4cCI6MjA2MzM5MDQ1MX0.Li01KuLN0F4hvUJhVIUNsm3zRg8zs7VtiM06cy2JgEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});